<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1;" />
<meta name="keywords" content="Client List" />
<meta name="description" content="Client List" />
<title>Client List</title>
<link rel="stylesheet" href="/styles/styles.css" type="text/css" />
</head>
<body>
<div id="wrapper"><h2><a href="/output/Page2.asp"><img alt="" height="70" src="../files/images/XM_logo.gif" title="XM London Digital Communication" width="162" /></a></h2><h2><img width="124" alt="Client list" height="80" border="0" src="/files/images/XM_L3_Clients_list_shdr.gif" /></h2><p>The case histories listed in this section, covers most of the types of projects we do from websites, intranets and extranets to Content Management Systems, CD-ROMs and pure consultancy projects. </p><p>The range of clients we work for is as varied as the solutions we have provided for them. We are particularly proud of the fact that the majority of our clients have worked with us continuously over the years.</p><ul class="clientsList"><li class="first"><strong>Not for profit Organisations</strong><ul><li>Arts Council</li><li><a href="/output/Page6.asp">Buckingham Palace</a></li><li><a href="/output/Page47.asp">Business in the Community</a></li><li><a href="/output/Page10.asp">Doha Debates</a></li><li><a href="/output/Page15.asp">HH Sheikha Mozzah</a></li><li>i-uk.com</li><li><a href="/output/Page48.asp">Kingston University</a></li><li><a href="/output/Page49.asp">National Trust</a></li><li><a href="/output/Page51.asp">Pensions Regulator</a></li><li><a href="/output/Page17.asp">Qatar Foundation</a></li></ul></li><li class="second"><strong>Corporate and Business to Business</strong><ul><li>Cable &amp; Wireless Virtual Academy</li><li>Central London Partnership</li><li><a href="/output/Page50.asp">Duchy of Lancaster</a></li><li>Mediaedge:cia</li><li>MindShare</li><li><a href="/output/Page13.asp">Platinum Guild</a></li><li>Rolls Royce PLC</li><li>SaBRE</li><li>Shell Nigeria</li></ul></li><li class="third"><strong>Marcoms Related</strong><ul><li><a href="/output/Page9.asp">Female Life</a></li><li>GlaxoSmithKline</li><li><a href="/output/Page12.asp">Harvey Nichols</a></li><li><a href="/output/Page18.asp">Ladbrokes</a></li><li>Levonelle</li><li>Liberty</li><li><a href="/output/Page16.asp">McCoy's</a></li><li><a href="/output/Page14.asp">Platinum Guild</a></li><li>Schering Pharma</li><li>Tia Lusso</li><li>Visit Britain</li></ul></li></ul><div class="clearleft"><br /></div><ul class="clientsList"><li class="first"><strong>Government</strong><ul><li>EU DG Trade</li><li><a href="/output/Page11.asp">HM Foreign and Commonwealth Office</a></li><li>HM Home Office</li><li>HM Privy Council</li><li>HM Treasury Solicitors</li><li>Leader of the House of Commons</li><li>UK Visas</li></ul></li><li class="second"><strong>Intranets and Extranets</strong><ul><li>Big Lottery Fund</li><li>FemaleLife</li><li>New Opportunity Fund</li><li>Pfizer</li><li>Platinum Guild</li><li>SaBRE</li></ul></li></ul><div class="clear"><br /></div></div>
</body>
</html>
