<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1;" />
<meta name="keywords" content="Awards" />
<meta name="description" content="Awards" />
<title>Awards</title>
<link rel="stylesheet" href="/styles/styles.css" type="text/css" />
<link rel="stylesheet" href="/styles/xm.css" type="text/css" />
</head>
<body><h2><a href="/output/Page2.asp"><img alt="" height="70" src="../files/images/XM_logo.gif" title="XM London Digital Communication" width="162" /></a></h2><h2><img width="108" alt="Awards" height="80" border="0" src="/files/images/XM_L3_Clients_awards_shdr.gif" /></h2><p>Over the past 10 years, we have featured in almost every industry award going and won many. In addition we have been short listed for many more.</p><p>Below is a quick overview of the types of the awards we have won.</p><table border="0" cellpadding="3" cellspacing="0" id="tblAwards" summary="Awards"><tr class="tblAwardsClear"><td><strong>Awards</strong></td><td align="center"><strong>Times<br />Won</strong></td><td align="left" valign="top"> </td><td><strong> </strong></td><td align="center"><strong>Times<br />Won</strong></td></tr><tr><td class="col1">Best Corporate Website for the Analyst</td><td class="col2">1</td><td align="left" valign="top"> </td><td class="col3">IPA Effectiveness Awards</td><td class="col4">2</td></tr><tr><td class="col1">Best Private Investor Website </td><td class="col2">1</td><td align="left" valign="top"> </td><td class="col3">IR Best Practice Award Private Investors</td><td class="col4">1</td></tr><tr><td class="col1">BIMA British Interactive Multimedia Awards</td><td class="col2">9</td><td align="left" valign="top"> </td><td class="col3">IVCA</td><td class="col4">3</td></tr><tr><td class="col1">BT Business Awards</td><td class="col2">1</td><td align="left" valign="top"> </td><td class="col3">London Advertising Awards</td><td class="col4">6</td></tr><tr><td class="col1">D&amp;AD</td><td class="col2">1</td><td align="left" valign="top"> </td><td class="col3">Clio Awards</td><td class="col4">6</td></tr><tr><td class="col1">Marketing Week Effectiveness Award Financial Services</td><td class="col2">1</td><td align="left" valign="top"> </td><td class="col3">MILIA Awards Grand Prix Milia d'Or BIMA</td><td class="col4">1</td></tr><tr><td class="col1">Financial Times Business Web Site of the Year</td><td class="col2">1</td><td align="left" valign="top"> </td><td class="col3">New Media Age Effectiveness Awards</td><td class="col4">4</td></tr><tr><td class="col1">Government Internet Forum Awards</td><td class="col2">4</td><td align="left" valign="top"> </td><td class="col3">One Show New York</td><td class="col4">3</td></tr><tr><td class="col1">International EMMA Awards</td><td class="col2">3</td><td align="left" valign="top"> </td><td class="col3"> </td><td class="col4"> </td></tr></table><div class="clear"></div>
<p class="printCenter">http://www.xmlondon.com</p>
<div class="clear"></div>
</body>
</html>
